<a href="https://colab.research.google.com/github/samiabat/ml-onboarding-task1/blob/main/Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [ ]:
#your code here
from itertools import combinations

elements = ['A', 'B', 'C']
combs = list(combinations(elements, 2))

print(combs)

[('A', 'B'), ('A', 'C'), ('B', 'C')]


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
#your code here
import itertools
lst =  ['Python', 'is', 'fun']
squence  = itertools.cycle(lst)

for _ in range(10):
  print(next(squence))


Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [ ]:
#your code here
import glob
for pyfile in glob.glob("*.py"):
  print(pyfile)

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [ ]:
#your code here
text = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
from bs4 import BeautifulSoup
soup = BeautifulSoup(text, 'html.parser')
paragraphs = soup.find_all('p')
for paragraph in paragraphs:
  print(paragraph.text)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [ ]:
#your code here
import re
text = "AI is very important technology"
replaced_text = re.sub(r'\b{}\b'.format(re.escape('AI')), "Artificial Intelligence", text)
print(replaced_text)

Artificial Intelligence is very important technology


**CP6**: Create a numpy array of 10 zeros.

In [ ]:
#your code here
import numpy as np
matrix = np.zeros(10)
matrix

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [ ]:
#your code here
import numpy as np
matrix = np.arange(10, 49+1)
matrix

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [ ]:
#your code here
import numpy as np
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

LLM(large language models) such as generetive AI needs a large amount of data.
Large data mean:- the dataset we provide should be very large to make the ai work as expected.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

1, Attack - we can use AI to find the pattern and crack some sequences that many security things works. eg. mobile card.

2, Deep fake - AI can act as some one or celebrities do something and may result in false information.

there should have government involment and the colaboration between the companies should be needed.